name: hello-world
on: [push]
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello using echo
        run: echo "$(<hello.txt)"
      - name: Hellon using cat
        run: cat hello.txt